read_globals = {
    -- Test.More
    'plan',
    'done_testing',
    'skip_all',
    'BAIL_OUT',
    'subtest',
    'diag',
    'note',
    'skip',
    'todo_skip',
    'skip_rest',
    'todo',
    -- Test.Assertion
    'equals',
    'not_equals',
    'array_equals',
    'is_cdata',
    'is_function',
    'is_number',
    'is_table',
    'same',
    'falsy',
    'truthy',
    'fails',
    'passes',
    'matches',
    'error_matches',
    'not_errors',
    'require_ok',
    -- testsuite
    'Point',
}
globals = {
    -- Coat
    'argerror',
    'checktype',
    'can',
    'isa',
    'does',
    'dump',
    'new',
    'instance',
    '_INIT',
    'has',
    'method',
    'overload',
    'override',
    'mock',
    'unmock',
    'before',
    'around',
    'after',
    'memoize',
    'bind',
    'extends',
    'with',
    'module',
    'class',
    'singleton',
    'abstract',
    'augment',
}
